<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Participant;
use Carbon\Carbon;

class ParticipantSeeder extends Seeder
{
    public function run(): void
    {
        Participant::insert([
            // Your existing participants
            [
                'nom' => 'Bennani',
                'prenom' => 'Karim',
                'telephone' => '0551234567',
                'adresse' => 'Rue 12, Alger',
                'date_naissance' => '1995-06-12',
                'ville' => 'Alger',
                'email' => 'karim.bennani@example.com',
                'sexe' => 'homme',
                'size' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Zerrouki',
                'prenom' => 'Nadia',
                'telephone' => '0559876543',
                'adresse' => 'Rue 8, Oran',
                'date_naissance' => '1992-04-05',
                'ville' => 'Oran',
                'email' => 'nadia.zerrouki@example.com',
                'sexe' => 'femme',
                'size' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Belaid',
                'prenom' => 'Yacine',
                'telephone' => '0561237890',
                'adresse' => 'Rue 3, Constantine',
                'date_naissance' => '2000-09-21',
                'ville' => 'Constantine',
                'email' => 'yacine.belaid@example.com',
                'sexe' => 'homme',
                'size' => 'XL',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 10 Additional participants with diverse data
            [
                'nom' => 'Mansouri',
                'prenom' => 'Leila',
                'telephone' => '0552345678',
                'adresse' => 'Avenue des Martyrs, Blida',
                'date_naissance' => '1988-11-15',
                'ville' => 'Blida',
                'email' => 'leila.mansouri@example.com',
                'sexe' => 'femme',
                'size' => 'S',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Khelifi',
                'prenom' => 'Rachid',
                'telephone' => '0553456789',
                'adresse' => 'Rue de la République, Tizi Ouzou',
                'date_naissance' => '1993-03-22',
                'ville' => 'Tizi Ouzou',
                'email' => 'rachid.khelifi@example.com',
                'sexe' => 'homme',
                'size' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Boucherit',
                'prenom' => 'Samira',
                'telephone' => '0554567890',
                'adresse' => 'Cité 200 logements, Béjaïa',
                'date_naissance' => '1997-07-30',
                'ville' => 'Béjaïa',
                'email' => 'samira.boucherit@example.com',
                'sexe' => 'femme',
                'size' => 'XS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Touati',
                'prenom' => 'Mehdi',
                'telephone' => '0555678901',
                'adresse' => 'Rue Abane Ramdane, Sétif',
                'date_naissance' => '1990-12-08',
                'ville' => 'Sétif',
                'email' => 'mehdi.touati@example.com',
                'sexe' => 'homme',
                'size' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Saadi',
                'prenom' => 'Fatima',
                'telephone' => '0556789012',
                'adresse' => 'Rue Didouche Mourad, Annaba',
                'date_naissance' => '1985-05-19',
                'ville' => 'Annaba',
                'email' => 'fatima.saadi@example.com',
                'sexe' => 'femme',
                'size' => 'XL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Hamidou',
                'prenom' => 'Salah',
                'telephone' => '0557890123',
                'adresse' => 'Cité Universitaire, Batna',
                'date_naissance' => '2002-01-25',
                'ville' => 'Batna',
                'email' => 'salah.hamidou@example.com',
                'sexe' => 'homme',
                'size' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Bouchenak',
                'prenom' => 'Yasmina',
                'telephone' => '0558901234',
                'adresse' => 'Rue de la Gare, Mostaganem',
                'date_naissance' => '1994-08-14',
                'ville' => 'Mostaganem',
                'email' => 'yasmina.bouchenak@example.com',
                'sexe' => 'femme',
                'size' => 'S',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Gacem',
                'prenom' => 'Nabil',
                'telephone' => '0559012345',
                'adresse' => 'Rue de la Plage, Jijel',
                'date_naissance' => '1987-02-28',
                'ville' => 'Jijel',
                'email' => 'nabil.gacem@example.com',
                'sexe' => 'homme',
                'size' => 'XXL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Benzine',
                'prenom' => 'Rym',
                'telephone' => '0550123456',
                'adresse' => 'Rue des Oliviers, Tipaza',
                'date_naissance' => '1999-10-07',
                'ville' => 'Tipaza',
                'email' => 'rym.benzine@example.com',
                'sexe' => 'femme',
                'size' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Mammeri',
                'prenom' => 'Tarek',
                'telephone' => '0551234509',
                'adresse' => 'Rue du Stade, Boumerdès',
                'date_naissance' => '1991-06-17',
                'ville' => 'Boumerdès',
                'email' => 'tarek.mammeri@example.com',
                'sexe' => 'homme',
                'size' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Boukhari',
                'prenom' => 'Sofia',
                'telephone' => '0552345601',
                'adresse' => 'Rue des Fleurs, Tlemcen',
                'date_naissance' => '1996-04-03',
                'ville' => 'Tlemcen',
                'email' => 'sofia.boukhari@example.com',
                'sexe' => 'femme',
                'size' => 'XS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}